services:
  neo4j:
    image: neo4j:5.22
    ports:
      - '7474:7474'
      - '7687:7687'
    volumes:
      - ./neo4j/data:/data
      - ./neo4j/conf:/conf
      - ./neo4j/logs:/logs
      - ./neo4j/plugins:/plugins
      - ./neo4j/import:/import
    environment:
      NEO4J_AUTH: 'neo4j/neo4jtest'
